
CREATE TABLE DBFDZ0
(
    Z0FLDID  CHAR(6)  NOT NULL,
    Z0FLDTYP CHAR(1)  NOT NULL,
    Z0FLDLEN SMALLINT NOT NULL,
    Z0DECLEN SMALLINT NOT NULL,
    Z0FLDDES VARCHAR(30)
);


ALTER TABLE DBFDZ0
   ADD CONSTRAINT DBFDZ0_PK Primary Key (
      Z0FLDID);



CREATE TABLE OTFDY1
(
    Y1TRSID    CHAR(6)  NOT NULL,
    Y1TRSNAM   VARCHAR(30),
    Y1TRSNME   VARCHAR(30),
    Y1SYSID    CHAR(3),
    Y1TRSTYP   CHAR(2),
    Y1TRSPGM   CHAR(10),
    Y1SRCTYP   CHAR(10),
    Y1RVKPGM   CHAR(10),
    Y1FLAGS    CHAR(20)
);


ALTER TABLE OTFDY1
   ADD CONSTRAINT OTFDY1_PK Primary Key (
      Y1TRSID);



CREATE TABLE OTFDY2
(
    Y2TRSID  CHAR(6)   NOT NULL,
    Y2FLDSEQ  SMALLINT  NOT NULL,
    Y2COMFLD   CHAR(8)   NOT NULL,
    Y2FLDRID  CHAR(6)   NOT NULL,
    Y2FLDDES  VARCHAR(30)
);


ALTER TABLE OTFDY2
   ADD CONSTRAINT OTFDY2_PK Primary Key (
      Y2TRSID, Y2FLDSEQ);



CREATE TABLE OTFDY3
(
    Y3TRSID  CHAR(6)   NOT NULL,
    Y3FLDSEQ  SMALLINT  NOT NULL,
    Y3COMFLD   CHAR(8)   NOT NULL,
    Y3FLDRID  CHAR(6)   NOT NULL,
    Y3FLDDES  VARCHAR(30)
);


ALTER TABLE OTFDY3
   ADD CONSTRAINT OTFDY3_PK Primary Key (
      Y3TRSID, Y3FLDSEQ);

