DELETE FROM DBFDZ0;

INSERT INTO DBFDZ0(Z0FLDID, Z0FLDTYP, Z0FLDLEN, Z0DECLEN, Z0FLDDES) 
    VALUES('OBJNAM','A', 10, 0,'AS400 OBJECT NAME');

INSERT INTO DBFDZ0(Z0FLDID, Z0FLDTYP, Z0FLDLEN, Z0DECLEN, Z0FLDDES) 
    VALUES('NUM_06','S', 6, 0, 'NUMBER');
 

DELETE FROM OTFDY1;

INSERT INTO OTFDY1(Y1TRSID, Y1TRSNAM, Y1TRSNME, Y1FLAGS) 
    VALUES('900002','IBANK SYNC DIFINITIONS', 'IBANK SYNC DIFINITIONS', '0');
    

DELETE FROM OTFDY2;

INSERT INTO OTFDY2(Y2TRSID, Y2FLDSEQ, Y2COMFLD, Y2FLDRID, Y2FLDDES) 
    VALUES('900002',1,'FILENAME','OBJNAM', 'FILE TO SEND ');


DELETE FROM OTFDY3;

INSERT INTO OTFDY3(Y3TRSID, Y3FLDSEQ, Y3COMFLD, Y3FLDRID, Y3FLDDES) 
    VALUES('900002', 1, 'TOTNUM', 'NUM_06', 'TOTOAL DOWNLOAD NUMBER');



